In [14]:
#write a function to compute / and use try/except to catch the exceptions. 
def myexcep(num):
    try:
     res=num/0
    except Exception as e:
     print(e)

In [15]:
myexcep(5)

division by zero


In [13]:
#Implement a Python program to generate all sentences where subject is in Americans Indians and verb is in Play watch
#and the object is in baseballcricket. Hint Subject,verb and Object should be declared in the program as shown below.  
#subectsAmericans Indians erbsplaywatch obectsaseballricet.
#Output should come as below:  
#Americans  play baseball. 
#Americans  play cricket. 
#Americans  watch baseball. 
#Americans  watch cricket. 
#Indians play baseball. 
#Indians play cricket. 
#Indians watch baseball. 
#Indians watch cricket. 

subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
print(str(subjects[0]+" "+verbs[0]+" "+objects[0]+"."))
print(str(subjects[0]+" "+verbs[0]+" "+objects[1]+"."))
print(str(subjects[0]+" "+verbs[1]+" "+objects[0]+"."))
print(str(subjects[0]+" "+verbs[1]+" "+objects[1]+"."))
print(str(subjects[1]+" "+verbs[0]+" "+objects[0]+"."))
print(str(subjects[1]+" "+verbs[0]+" "+objects[1]+"."))
print(str(subjects[1]+" "+verbs[1]+" "+objects[0]+"."))
print(str(subjects[1]+" "+verbs[1]+" "+objects[1]+"."))

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [1]:
import numpy as np
def mymat(l):
    print("Input Vector:",l)
    noc=3
    l1=np.array([l])
    l2=l1.size
    print("Input Vector Size:",l2)
    bool=False
    l3=np.column_stack([x**(noc-1-i) for x in l1 for i in range(noc) if bool==False]).reshape(l2,noc)
    print("Output Matrix:\n\n",l3,"\n")
    return l3   

In [2]:
l2=[1,2,3,4]
mymat(l2)

Input Vector: [1, 2, 3, 4]
Input Vector Size: 4
Output Matrix:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 



array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)